# Generated by Django 2.2.14 on 2022-04-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.BooleanField(verbose_name='You got this resposibility')),
                ('user', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('option', models.CharField(choices=[('It happened to me', 'It happened to me'), ("It's already been like that", "It's already been like that")], max_length=100)),
                ('reason', models.CharField(choices=[('Delete patient', 'Delete patient'), ('System problems', 'System problems'), ('Other', 'Others')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('situation', models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
